//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSqlEntityExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class dog
    {
        public int Id { get; set; }
        public string Dogname { get; set; }
        public string Dogowner { get; set; }
    }
}
